apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LexLandau/homelab-k3s.git
    targetRevision: main
    path: kubernetes/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false  # Manuell f√ºr Home Apps
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
