apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  namespace: terraria
  labels:
    app: terraria
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
      - name: terraria
        image: ryshe/terraria:latest
        ports:
        - containerPort: 7777
          name: game
          protocol: TCP
        # Original Entrypoint nutzen!
        env:
        - name: WORLD_FILENAME
          value: "world.wld"
        - name: AUTOCREATE
          value: "3"
        - name: WORLDNAME
          value: "K3s-World"
        volumeMounts:
        - name: terraria-data
          mountPath: /root/.local/share/Terraria/Worlds
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: terraria-data
        persistentVolumeClaim:
          claimName: terraria-data
