apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Longhorn
  - longhorn/longhorn.yaml
  - longhorn/storageclass-fast.yaml
  # MetalLB
  - metallb/metallb-native.yaml
  - metallb/ipaddresspool.yaml
  - metallb/l2advertisement.yaml
