allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"longhorn-jellyfin-nvme"},"parameters":{"dataLocality":"strict-local","diskSelector":"nvme","fsType":"ext4","nodeSelector":"nvme","numberOfReplicas":"1","staleReplicaTimeout":"2880"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
  creationTimestamp: "2025-12-15T16:33:35Z"
  name: longhorn-jellyfin-nvme
  resourceVersion: "5421322"
  uid: 55f020e9-a3be-48c8-b522-a7e159c1050f
parameters:
  dataLocality: strict-local
  diskSelector: nvme
  fsType: ext4
  nodeSelector: nvme
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
