apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-toml-config
  namespace: pihole
data:
  pihole.toml: |
    [dns]
    cache.size = 50000
    cache.optimizer = 3600
    upstreams = ["1.1.1.1", "1.0.0.1", "9.9.9.9", "192.168.1.1"]
    
    [webserver]
    port = 80
    
    [database]
    maxDBdays = 365
