# WICHTIG: Dieses File NICHT ins Git committen!
# Secret manuell erstellen:
# 
# kubectl create secret generic pihole-password \
#   --from-literal=password='DEIN_SICHERES_PASSWORT' \
#   -n pihole
#
# Oder aus 1Password:
# kubectl create secret generic pihole-password \
#   --from-literal=password="$(op item get 'Pi-hole Admin' --fields password)" \
#   -n pihole
