apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-nvme
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-jellyfin-nvme
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-nvme
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-jellyfin-nvme
  resources:
    requests:
      storage: 10Gi
