---
# K3s cluster configuration

k3s_token_file: "{{ playbook_dir }}/../.k3s-token"

# All nodes are control plane + worker (no taints)
k3s_server_options:
  - "--disable=traefik"
  - "--disable=servicelb"
  - "--write-kubeconfig-mode=644"
  - "--cluster-init"
  - "--tls-san={{ ansible_host }}"
  - "--node-ip={{ ansible_host }}"
  - "--flannel-iface=eth0"

# Network
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
metallb_ip_range: "192.168.1.220-192.168.1.239"

# Versions (January 2026)
k3s_version: v1.33.6+k3s1
argocd_version: v2.13.2
longhorn_version: v1.10.1
metallb_version: v0.15.3

timezone: Europe/Berlin

github_repo_url: "https://github.com/LexLandau/homelab-k3s.git"
github_repo_branch: main
